# Generated by Django 3.0.3 on 2020-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Code', models.CharField(max_length=264, unique=True)),
                ('Name', models.CharField(max_length=264, unique=True)),
                ('Gender', models.CharField(max_length=264, unique=True)),
                ('Age', models.CharField(max_length=264, unique=True)),
                ('Birth_Date', models.CharField(max_length=264, unique=True)),
                ('Photo', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
