# Generated by Django 3.0.3 on 2020-05-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200520_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Joining_Date', models.CharField(max_length=264, unique=True)),
                ('Confirmation_Date', models.CharField(max_length=264, unique=True)),
                ('Probation_Date', models.CharField(max_length=264, unique=True)),
                ('Last_Increment_Given_On', models.CharField(max_length=264, unique=True)),
                ('Employment_status', models.CharField(max_length=264, unique=True)),
                ('Resign_offer_Date', models.CharField(max_length=264, unique=True)),
                ('employee_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee_detail')),
            ],
        ),
    ]
