# Generated by Django 3.0.3 on 2020-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200521_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='Birth_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employment_detail',
            name='Confirmation_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employment_detail',
            name='Joining_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employment_detail',
            name='Last_Increment_Given_On',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employment_detail',
            name='Probation_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employment_detail',
            name='Resign_offer_Date',
            field=models.DateField(),
        ),
    ]
