# Generated by Django 3.0.3 on 2020-05-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200521_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='Age',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='Gender',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='Photo',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='employment_detail',
            name='Employment_status',
            field=models.CharField(max_length=264),
        ),
    ]
