# Generated by Django 3.0.3 on 2020-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200521_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='Photo',
            field=models.BooleanField(default=False, verbose_name='Photo'),
        ),
    ]
