# Generated by Django 3.0.3 on 2020-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200521_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_detail',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_detail',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee_detail',
            name='integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='Photo',
            field=models.CharField(max_length=264),
        ),
    ]
