# Generated by Django 3.0.3 on 2020-05-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200521_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_detail',
            name='datetime',
        ),
    ]
