# Generated by Django 3.0.3 on 2020-05-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_employee_detail_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Code', models.CharField(max_length=264, unique=True)),
                ('Name', models.TextField()),
                ('Gender', models.CharField(max_length=264)),
                ('Age', models.CharField(max_length=264)),
                ('Birth_Date', models.DateField()),
                ('boolean', models.BooleanField(default=False)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='blog/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Joining_Date', models.DateField()),
                ('Confirmation_Date', models.DateField()),
                ('Probation_Date', models.DateField()),
                ('Last_Increment_Given_On', models.DateField()),
                ('Employment_status', models.CharField(max_length=264)),
                ('Resign_offer_Date', models.DateField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='employment_detail',
            name='employee_detail',
        ),
        migrations.DeleteModel(
            name='employee_detail',
        ),
        migrations.DeleteModel(
            name='Employment_Detail',
        ),
    ]
